# Generated by Django 4.1.7 on 2023-02-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Use',
        ),
        migrations.AddField(
            model_name='playlist',
            name='use',
            field=models.CharField(default='anon', max_length=60),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
